on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Generate README.md
      env:
        USER_TOKEN: ${{ secrets.USER_TOKEN }}
      run: |
            echo "is_MY_SECRET_set: ${{ env.MY_SECRET != '' }}"
            echo "::set-output name=is_MY_SECRET_set::${{ env.MY_SECRET != '' }}"
